name: ci

on: push

env:
  mold_version: "1.3.0"

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download from Github release
      run: |
        wget -c -q https://github.com/ren15/mold_ci/releases/download/latest/mold.tar.gz
        tar xvf mold.tar.gz
        make build
        image_name="centos:7" make test


    - uses: actions/upload-artifact@v2
      with:
        name: lib-package
        path: lib-package.tar.gz

  test:
    runs-on: ubuntu-20.04
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "ubuntu:20.04",
            "ubuntu:14.04",
            "debian:8",
            "centos:7",
            "rockylinux:8",
            "fedora:35",
            "archlinux:latest",
            "alpine:latest",
            "busybox:latest",
          ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: lib-package
    - name: Download from github release
      run: |
        wget -c -q https://github.com/ren15/mold_ci/releases/download/latest/mold.tar.gz
        tar xvf mold.tar.gz
        ls 
        tar xvf lib-package.tar.gz
        ls -lah package
        image_name="${{ matrix.container_image }}" make test
