name: ci

on: push

env:
  mold_version: "1.2.0"

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download from github release
      run: |
        wget -c -q https://github.com/ren15/mold_ci/releases/download/latest/mold.tar.gz
        tar xvf mold.tar.gz
        make build
        make test


    - uses: actions/upload-artifact@v2
      with:
        name: lib-package
        path: lib-package.tar.gz

  test_deb:
    runs-on: ubuntu-20.04
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "ubuntu:20.04",
            "ubuntu:16.04",
            "ubuntu:14.04",
            "debian:10",
            "debian:9",
            "debian:8",
          ]
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: lib-package
    - name: Download from github release
      run: |
        apt update && apt install -y tar wget
        wget -c -q https://github.com/ren15/mold_ci/releases/download/latest/mold.tar.gz
        tar xvf mold.tar.gz
        ls 
        tar xvf lib-package.tar.gz
        ls -lah package
        package/ld-linux-x86-64.so.2 --library-path ${PWD}/package ./mold --version

  test_rpm:
    runs-on: ubuntu-20.04
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "centos:7",
            "centos:6",
            "rockylinux:8",
            "fedora:35",
          ]
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: lib-package
    - name: Download from github release
      run: |
        yum install -y tar wget 
        wget -c -q https://github.com/ren15/mold_ci/releases/download/latest/mold.tar.gz
        tar xvf mold.tar.gz
        ls 
        tar xvf lib-package.tar.gz
        ls -lah package
        package/ld-linux-x86-64.so.2 --library-path ${PWD}/package ./mold --version